export const SEND_GITHUB_CODE = {
  started: 'SEND_GITHUB_CODE_STARTED',
  success: 'SEND_GITHUB_CODE_SUCCESS',
  failed: 'SEND_GITHUB_CODE_FAILED',
};

export const BIND_TELEGRAM_PROFILE = {
  started: 'BIND_TELEGRAM_PROFILE_STARTED',
  success: 'BIND_TELEGRAM_PROFILE_SUCCESS',
  failed: 'BIND_TELEGRAM_PROFILE_FAILED',
};

export const BIND_SLACK_PROFILE = {
  started: 'BIND_SLACK_PROFILE_STARTED',
  success: 'BIND_SLACK_PROFILE_SUCCESS',
  failed: 'BIND_SLACK_PROFILE_FAILED',
};

export const BIND_TELEGRAM_PROJECT = {
  started: 'BIND_TELEGRAM_PROJECT_STARTED',
  success: 'BIND_TELEGRAM_PROJECT_SUCCESS',
  failed: 'BIND_TELEGRAM_PROJECT_FAILED',
};

export const BIND_SLACK_PROJECT = {
  started: 'BIND_SLACK_PROJECT_STARTED',
  success: 'BIND_SLACK_PROJECT_SUCCESS',
  failed: 'BIND_SLACK_PROJECT_FAILED',
};

export const UNBIND_SLACK_PROFILE = {
  started: 'UNBIND_SLACK_PROFILE_STARTED',
  success: 'UNBIND_SLACK_PROFILE_SUCCESS',
  failed: 'UNBIND_SLACK_PROFILE_FAILED',
};

export const UNBIND_TELEGRAM_PROFILE = {
  started: 'UNBIND_TELEGRAM_PROFILE_STARTED',
  success: 'UNBIND_TELEGRAM_PROFILE_SUCCESS',
  failed: 'UNBIND_TELEGRAM_PROFILE_FAILED',
};

export const BIND_REPO_TO_PROJECT = {
  started: 'BIND_REPO_TO_PROJECT_STARTED',
  success: 'BIND_REPO_TO_PROJECT_SUCCESS',
  failed: 'BIND_REPO_TO_PROJECT_FAILED',
};

export const UNBIND_SLACK_PROJECT = {
  started: 'UNBIND_SLACK_PROJECT_STARTED',
  success: 'UNBIND_SLACK_PROJECT_SUCCESS',
  failed: 'UNBIND_SLACK_PROJECT_FAILED',
};

export const UNBIND_TELEGRAM_PROJECT = {
  started: 'UNBIND_TELEGRAM_PROJECT_STARTED',
  success: 'UNBIND_TELEGRAM_PROJECT_SUCCESS',
  failed: 'UNBIND_TELEGRAM_PROJECT_FAILED',
};
