export const GET_MARKETPLACE_PRODUCTS = {
  started: 'GET_MARKETPLACE_PRODUCTS_STARTED',
  success: 'GET_MARKETPLACE_PRODUCTS_SUCCESS',
  failed: 'GET_MARKETPLACE_PRODUCTS_FAILED',
};

export const ADD_MARKETPLACE_PRODUCT = {
  started: 'ADD_MARKETPLACE_PRODUCT_STARTED',
  success: 'ADD_MARKETPLACE_PRODUCT_SUCCESS',
  failed: 'ADD_MARKETPLACE_PRODUCT_FAILED',
};

export const DELETE_MARKETPLACE_PRODUCT = {
  started: 'DELETE_MARKETPLACE_PRODUCT_STARTED',
  success: 'DELETE_MARKETPLACE_PRODUCT_SUCCESS',
  failed: 'DELETE_MARKETPLACE_PRODUCT_FAILED',
};

export const GET_CART_ITEMS = {
  started: 'GET_CART_ITEMS_STARTED',
  success: 'GET_CART_ITEMS_SUCCESS',
  failed: 'GET_CART_ITEMS_FAILED',
};

export const ADD_TO_CART = {
  started: 'ADD_TO_CART_STARTED',
  success: 'ADD_TO_CART_SUCCESS',
  failed: 'ADD_TO_CART_FAILED',
};

export const DELETE_FROM_CART = {
  started: 'DELETE_FROM_CART_STARTED',
  success: 'DELETE_FROM_CART_SUCCESS',
  failed: 'DELETE_FROM_CART_FAILED',
};
