export const GET_MARKETPLACE_PRODUCTS = {
  started: 'GET_MARKETPLACE_PRODUCTS_STARTED',
  success: 'GET_MARKETPLACE_PRODUCTS_SUCCESS',
  failed: 'GET_MARKETPLACE_PRODUCTS_FAILED',
};

export const ADD_MARKETPLACE_PRODUCT = {
  started: 'ADD_MARKETPLACE_PRODUCT_STARTED',
  success: 'ADD_MARKETPLACE_PRODUCT_SUCCESS',
  failed: 'ADD_MARKETPLACE_PRODUCT_FAILED',
};
